"""esquema inicial

Revision ID: 8dba8a845113
Revises: 
Create Date: 2026-09-06 11:17:07.457348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dba8a845113'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odontologos',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('apellido_odontologo', sa.String(length=50), nullable=False),
    sa.Column('nombre_odontologo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('domicilio', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('obrasocial', sa.String(length=50), nullable=True),
    sa.Column('nrosocio', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('fechanacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('pass_usuario', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('odontogramas',
    sa.Column('id_odontograma', sa.Integer(), nullable=False),
    sa.Column('dni_paciente', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('odontologo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dni_paciente'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['odontologo'], ['odontologos.matricula'], ),
    sa.PrimaryKeyConstraint('id_odontograma')
    )
    op.create_table('prestaciones',
    sa.Column('id_prestacion', sa.Integer(), nullable=False),
    sa.Column('tipo_prestacion', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('paciente', sa.Integer(), nullable=False),
    sa.Column('odontologo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['odontologo'], ['odontologos.matricula'], ),
    sa.ForeignKeyConstraint(['paciente'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id_prestacion')
    )
    op.create_table('turnos',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('paciente', sa.String(length=100), nullable=False),
    sa.Column('odontologo', sa.Integer(), nullable=False),
    sa.Column('prestacion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['odontologo'], ['odontologos.matricula'], ),
    sa.PrimaryKeyConstraint('fecha', 'hora')
    )
    op.create_table('dientes',
    sa.Column('nro', sa.Integer(), nullable=False),
    sa.Column('nro_diente', sa.Integer(), nullable=True),
    sa.Column('id_odonto', sa.Integer(), nullable=True),
    sa.Column('d', sa.String(length=20), nullable=True),
    sa.Column('v', sa.String(length=20), nullable=True),
    sa.Column('m', sa.String(length=20), nullable=True),
    sa.Column('i', sa.Float(), nullable=True),
    sa.Column('o', sa.Integer(), nullable=True),
    sa.Column('extraccion', sa.String(length=20), nullable=True),
    sa.Column('corona', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_odonto'], ['odontogramas.id_odontograma'], ),
    sa.PrimaryKeyConstraint('nro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dientes')
    op.drop_table('turnos')
    op.drop_table('prestaciones')
    op.drop_table('odontogramas')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('odontologos')
    # ### end Alembic commands ###
